gridWorkingDir:			workingdir_test2
gridOutputDir:			outputdir_19i3c1_pthat4
# aliROOTVersion:         v5-09-54a-2
aliPhysicsVersion:      vAN-20200629-1
package:                fastjet::v3.2.1_1.024-alice3-2
# package:                GCC-Toolchain::v7.3.0-alice2-7
# package:                boost::v1.72.0-alice1-1
gridDataDir:			/alice/data/2018/LHC18q
dataPattern:      /pass3/AOD/*/AliAOD.root
runPrefix:        000
runNumber:				[296621]
# runNumber:			[296623, 296622, 296621, 296619, 296618, 296616, 296615, 296594, 296553, 296552, 296551, 296550, 296548, 296547, 296516, 296512, 296511, 296509, 296472, 296433, 296420, 296419, 296415, 296414, 296383, 296381, 296380, 296379, 296376, 296375, 296312, 296307, 296304, 296303, 296280, 296273, 296270, 296247, 296244, 296243, 296242, 296241, 296240, 296198, 296197, 296196, 296195, 296192, 296191, 296143, 296142, 296135, 296134, 296133, 296132, 296123, 296074, 296068, 296066, 296065, 296063, 296062, 296060, 296016, 295942, 295941, 295937, 295936, 295913, 295909, 295908, 295881, 295860, 295859, 295856, 295855, 295854, 295853, 295831, 295825, 295822, 295819, 295818, 295816, 295791, 295788, 295786, 295763, 295762, 295759, 295758, 295755, 295754, 295725, 295723, 295721, 295719, 295718, 295717, 295714, 295712, 295677, 295676, 295675, 295673, 295671, 295668, 295667, 295666, 295665, 295615, 295612, 295611, 295610, 295589, 295588, 295587, 295586, 295585]
emcalCorrection:    emcal_correction_embed.yaml
emcalGeometryFilename:  	geometry_2015.root
emcalLocal2MasterFilename:  	EMCALlocal2master.root
skimClusterMinE:        15.0
splitMaxInputFileNumber: 4
isMC: false
isEmbed: true

# settings for embedding - only one should be active at a time
# file list for running locally - do not use alien
# embedLocalFileList:      pp-filelist-19i3a.txt
# file pattern for running on grid - do not run in test mode
embedGridFilePattern:   alien:///alice/sim/2019/LHC19i3c1/4